language: python


matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 2.7.6
          env: TOXENV=py27 VENDOR=no
        - python: 2.7.8
          env: TOXENV=py27 VENDOR=no
        - python: 2.7.9
          env: TOXENV=py27 VENDOR=no
        - python: 2.7.10
          env: TOXENV=py27 VENDOR=no
        - python: 3.3
          env: TOXENV=py33 VENDOR=no
        - python: 3.4
          env: TOXENV=py34 VENDOR=no
        - python: 3.5
          env: TOXENV=py35 VENDOR=no
        - python: 2.7
          env: TOXENV=py27 VENDOR=no WHEELS=yes
        - python: 3.5
          env: TOXENV=py35 VENDOR=no WHEELS=yes


install: .travis/install.sh


script: .travis/run.sh


notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The actual value here is: irc.freenode.org#pypa-dev
      - secure: "zAlwcmrDThlRsZz7CPDGpj4ABTzf7bc/zQXYtvIuqmSj0yJMAwsO5Vx/+qdTGYBvmW/oHw2s/uUgtkZzntSQiVQToKMag2fs0d3wV5bLJQUE2Si2jnH2JOQo3JZWSo9HOqL6WYmlKGI8lH9FVTdVLgpeJmIpLy1bN4zx4/TiJjc="
    use_notice: true
    skip_join: true
